---
title: "Untitled"
author: "김희수"
date: "2019년 4월 11일"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(raster)
library(rgeos)
library(maptools)
```

## R Markdown

```{r cars}

A1 <- read.csv("../doc/hong1.csv")
A2 <- A1
A2[,2:ncol(A1)] <- t(apply(A1[,-1],1,function(x)cumsum(x))) #세로로 누적
A3 <- as.data.frame(apply(A1[,-1],1,function(x)cumsum(x)))
colnames(A3) <- A2$locate
A3$op <- c("id",paste0("week",1:52))

colnames(A2) <- c("locate","id",paste0("week",1:52))
A2$id <- c(0:6,8:16,7) #merge용 id부여

```

## Merge & Paint

```{r }

korea <- shapefile("../data/TL_SCCO_CTPRVN.shp")
korea <- spTransform(korea,CRS("+proj=longlat"))
korea_map <- fortify(korea)
merge_result <- merge(korea_map,A2,by='id')



```

## Get gif (Animation)

```{r }

plot <- function(ok,long,lat,group){
  ggplot() +
    geom_polygon(data = merge_result,
                 aes(x=long,y=lat,
                            group=group,
                            fill = ok))}

library(magick)

list.files(path = "../pic/", pattern = "*.png", full.names = T) %>%
  image_join(.) %>%
  image_animate(fps=2) %>%
  image_write("A1.gif")

```

## Neural Networks From 'NNET' Package

```{r}
getDataSet<-function(item,from,to,size){
  dataframe<-NULL
  to<-to-size+1
  for(i in from:to) {
    start<-i
    end<-start+size-1
    temp<-item[c(start:end)]
    dataframe<-rbind(dataframe,t(temp))
  }
  return(dataframe)
}

INPUT_NODES<-4
HIDDEN_NODES<-INPUT_NODES*2
OUTPUT_NODES<-2
ITERATION<-500

in_learning<-getDataSet(A3$전남,1,8,INPUT_NODES)
in_learning 

out_learning<-getDataSet(A3$전남,3,8,OUTPUT_NODES)
out_learning

model<-nnet(in_learning,out_learning,size=HIDDEN_NODES,linout = TRUE,rang = 0.1,skip=TRUE,maxit = ITERATION)

in_forecasting<-getDataSet(A3$전남,5,8,INPUT_NODES)
in_forecasting

predicted_values<-predict(model,in_forecasting,type="raw")
predicted_values

real<-getDataSet(A3$전남,8,9,OUTPUT_NODES)
real

ERR<-abs(real-predicted_values)
MAPE<-mean(ERR/real)*100
MAPE

plot(c(1:2),real, type="o", col="blue")
lines(c(1:2),predicted_values, type="o", col="red")

#예측

in_learning<-getDataSet(A3$전남,1,18,INPUT_NODES)
in_learning


out_learning<-getDataSet(A3$전남,5,20,OUTPUT_NODES)
out_learning

model<-nnet(in_learning,out_learning,size=HIDDEN_NODES,linout = TRUE,rang = 0.1,skip=TRUE,maxit = ITERATION)


in_forecasting<-getDataSet(A3$전남,17,20,INPUT_NODES)
in_forecasting

predicted_values<-predict(model,in_forecasting,type="raw")
predicted_values

real<-A3$전남[19:20]
real

plot(1:2,real,xlab="주차",ylab="발생수",ylim = c(2000,3000),type="o")
lines(2:3,predicted_values,type="o",col="red")
grid()
plot(11:20,A3[11:20,13],ylim = c(0,3000))
lines(19:20,predicted_values,type="o",col="red")
```


```{r}
p <- ggplot() +
  geom_polygon(data = merge_result,
               aes(x=long,y=lat,group=group, fill = week15)) +
  scale_fill_gradient(low = 'white',high='orange',limits = c(0,160))

p

ggsave(filename = paste0("../pic/OK_",15,".png"),
       width = 7,height=7,dpi = 150)


```